apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudtasks-ingress
  namespace: cloudtasks
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudtasks-service
            port:
              number: 80